GET https://localhost:3200/movies


###


GET https://movies-posbackend.herokuapp.com/movies


###


POST https://movies-posbackend.herokuapp.com/movies 
Content-Type: application/json

{
    "name": "The Mummy",
    "price": 95.00,
    "category": "Horror",
    "img": "https://i.postimg.cc/x8qMCxDs/the-conjuring.jpg",
    "description": "sgdhcshdch",
    "created_by": ""

}


###


PATCH http://localhost:3200/movies
Content-Type: application/json

{

}


###


DELETE http://localhost:3200/movies
###

# movies end


GET http://localhost:3200/user

###


POST http://localhost:3200/user/signin
Content-Type: application/json

{
    "fullname": "kyle mcbby",
    "password": "kyliej1"
}


###


POST http://localhost:3200/user/signup
Content-Type: application/json

{
    
    "fullname": "kyle mcbby",
    "password": "kyliej1",
    "email": "kkmwah@gmail.com",
    "phone_number": "0214223478"
    

}


###


PATCH http://localhost:3200/user
Content-Type: application/json

{

}


###

DELETE http://localhost:3200/user